[package]
name = "sparse-vectors-experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
ordered-float = "3.7.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
float-cmp = "0.9.0"

[profile.test]
opt-level = 3